"""tabla ganador

Registro de quién ganó, con qué cartón y con qué forma. Es la última entidad que
`docs/08-modelo-datos.md` pide para la Fase 1.

Revision ID: 6ea4bcdea815
Revises: b55a5f38ac38
Create Date: 2026-08-01 15:45:04.794648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea4bcdea815'
down_revision: Union[str, Sequence[str], None] = 'b55a5f38ac38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ganador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('carton_id', sa.Integer(), nullable=False),
    sa.Column('partida_figura_id', sa.Integer(), nullable=False),
    sa.Column('orden_balota', sa.Integer(), nullable=False),
    sa.Column('numero_balota', sa.Integer(), nullable=False),
    # sa.func.now() y no el sa.text('(CURRENT_TIMESTAMP)') que autogenera
    # Alembic: ese es específico de SQLite y rompería en PostgreSQL.
    sa.Column('detectado_en', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['carton_id'], ['carton.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partida_figura_id'], ['partida_figura.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partida_id', 'carton_id', 'partida_figura_id', name='uq_ganador')
    )
    with op.batch_alter_table('ganador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ganador_carton_id'), ['carton_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ganador_partida_figura_id'), ['partida_figura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ganador_partida_id'), ['partida_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ganador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ganador_partida_id'))
        batch_op.drop_index(batch_op.f('ix_ganador_partida_figura_id'))
        batch_op.drop_index(batch_op.f('ix_ganador_carton_id'))

    op.drop_table('ganador')
    # ### end Alembic commands ###
