"""tabla carton

Revision ID: 9433f6e50973
Revises: f925752e4a07
Create Date: 2026-07-30 14:15:35.845983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9433f6e50973'
down_revision: Union[str, Sequence[str], None] = 'f925752e4a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=8), nullable=False),
    sa.Column('numero_carton', sa.Integer(), nullable=False),
    sa.Column('numeros', sa.JSON(), nullable=False),
    sa.Column('firma', sa.String(length=64), nullable=False),
    # func.now() y no el literal (CURRENT_TIMESTAMP) que genera el
    # autogenerador: cada motor lo traduce a su sintaxis.
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partida_id', 'firma', name='uq_carton_firma'),
    sa.UniqueConstraint('partida_id', 'serie', 'numero_carton', name='uq_carton_numero')
    )
    with op.batch_alter_table('carton', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carton_firma'), ['firma'], unique=False)
        batch_op.create_index(batch_op.f('ix_carton_partida_id'), ['partida_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carton', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carton_partida_id'))
        batch_op.drop_index(batch_op.f('ix_carton_firma'))

    op.drop_table('carton')
    # ### end Alembic commands ###
