"""tablas partida y partida_figura

Revision ID: f925752e4a07
Revises: 42752ec6d6d0
Create Date: 2026-07-30 12:44:28.416852

Notas:
- Los `server_default` usan `sa.func.now()` en vez del literal
  `(CURRENT_TIMESTAMP)` que genera el autogenerador, para que la migración sirva
  igual en SQLite y en PostgreSQL.
- Los enums se guardan como texto (`native_enum=False`), no como el tipo ENUM
  nativo: SQLite no lo tiene y en PostgreSQL cambiar sus valores obliga a una
  migración incómoda.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f925752e4a07'
down_revision: Union[str, Sequence[str], None] = '42752ec6d6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_consecutivo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_curso', 'pausada', 'finalizada', name='estadopartida', native_enum=False, length=20), nullable=False),
    sa.Column('precio_carton', sa.Integer(), nullable=False),
    sa.Column('duracion_segundos_entre_balota', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizada_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_consecutivo'),
    # Evita que SQLite reutilice el id de una fila borrada; de ahí sale un
    # consecutivo de partida que nunca se repite.
    sqlite_autoincrement=True,
    )
    op.create_table('partida_figura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('figura_id', sa.Integer(), nullable=False),
    sa.Column('tipo_premio', sa.Enum('sencillo', 'figura', 'pleno', name='tipopremio', native_enum=False, length=20), nullable=False),
    sa.Column('valor_premio', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['figura_id'], ['figura.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partida_id', 'figura_id', name='uq_partida_figura')
    )
    with op.batch_alter_table('partida_figura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partida_figura_figura_id'), ['figura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partida_figura_partida_id'), ['partida_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partida_figura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partida_figura_partida_id'))
        batch_op.drop_index(batch_op.f('ix_partida_figura_figura_id'))

    op.drop_table('partida_figura')
    op.drop_table('partida')
    # ### end Alembic commands ###
